@startuml
'https://plantuml.com/class-diagram

hide methods

entity "Категория комплектующих" as componentCategory {
    Название
}
entity "Комплектующий" as component {
    Название
    Параметры : json
    ..
    Стоимость производителя
    Гарантия производителя
}
component }o--|| componentCategory

entity "Сборка" as configuration {
    Гарантия магазина
    Наценка
}
configuration }o--|{ component

entity "Покупатель" as customer {
    Имя
    Контактные данные : json
    Дата регистрации
}

entity "Продажа" as sale {
    Дата продажи
    Скидка
    Платежи : array
} 
sale }|--|| customer

entity "Позиция продажи" as salePosition {
    Стоимость
    Скидка
    Гарантия
}
salePosition }|--|| sale
salePosition }o--|| configuration

@enduml
